# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  azure-acr: circleci/azure-acr@0.2.0 
  windows: circleci/windows@2.4.0

jobs:
  test:
    description: Setup and run application tests 
    executor: 
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
          working_directory: Tailspin.SpaceGame.Web
      - run: 
          command: dotnet build 
          working_directory: Tailsping.SpaceGame.Test
      - run:
          name: "Run application tests"
          command: dotnet.exe test -v n --results-directory:test_coverage
          working_directory: Tailsping.SpaceGame.Test
      - run: dir Tailsping.SpaceGame.Test
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
      - store_test_results:
          path: C:\Users\circleci\project\test_coverage

  build-and-push:
    description: Build Docker container image and push to registry
    executor:
      name: azure-acr/default
    steps:
      - azure-acr/build-and-push-image:
          checkout: true
          login-server-name: beekeepertest.azurecr.io
          registry-name: beekeepertest
          repo: circleci-game
          tag: latest
          azure-sp: AZURE_SP
          azure-sp-password: AZURE_SP_PASSWORD
          azure-sp-tenant: AZURE_SP_TENANT
          dockerfile: ./Tailspin.SpaceGame.Web/Dockerfile

workflows:
  test_and_build:
    jobs:
      - test
      - build-and-push:
          requires: 
            - test