# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  azure-acr: circleci/azure-acr@0.2.0 

workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: beekeepertest.azurecr.io
          registry-name: beekeepertest
          repo: circleci-game
          tag: latest
          azure-password: beeadmin
          azure-username: FS03Dbp7ZhUQLDsk+gM2IvWPbtlxymBV
