name: dotnet package 

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix:
        dotnet-version: ['3.1.x']

    steps:
    - uses: actions/checkout@v2

    - name: Set .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version:${{matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} --no-restore #--output ${{env.SOLUTION_FILE_PATH}}
